### PR TITLE
Add Accessibity

### PR DESCRIPTION
**Pull request by Katended**
The following have been addressed in the pull request:

- Page titles:

   Updated the title of the page to be more descriptive 

   [https://github.com/Katended/mobilefirstproject2/pull/8/files#diff-ba9f3fbde9c0c98a09b8fcb805a096ed053753a7b7d2844dca83ad9907e720ccR7](https://github.com/Katended/mobilefirstproject2/pull/8/files#diff-ba9f3fbde9c0c98a09b8fcb805a096ed053753a7b7d2844dca83ad9907e720ccR7)

- Image text alternatives:
Added image alt-text to project images:

   [https://github.com/Katended/mobilefirstproject2/pull/8/files#diff-ba9f3fbde9c0c98a09b8fcb805a096ed053753a7b7d2844dca83ad9907e720ccR7](https://github.com/Katended/mobilefirstproject2/pull/8/files#diff-ba9f3fbde9c0c98a09b8fcb805a096ed053753a7b7d2844dca83ad9907e720ccR7)

   [https://github.com/Katended/mobilefirstproject2/pull/8/files#diff-ba9f3fbde9c0c98a09b8fcb805a096ed053753a7b7d2844dca83ad9907e720ccR99](https://github.com/Katended/mobilefirstproject2/pull/8/files#diff-ba9f3fbde9c0c98a09b8fcb805a096ed053753a7b7d2844dca83ad9907e720ccR99)

   [https://github.com/Katended/mobilefirstproject2/pull/8/files#diff-ba9f3fbde9c0c98a09b8fcb805a096ed053753a7b7d2844dca83ad9907e720ccR99](https://github.com/Katended/mobilefirstproject2/pull/8/files#diff-ba9f3fbde9c0c98a09b8fcb805a096ed053753a7b7d2844dca83ad9907e720ccR99)

- Text headings
   No Issues

- Color contrast
  No Issues

- Resize
   Removed size property in first section to prevent link overlaps on when page is zoomed.

   [https://github.com/Katended/mobilefirstproject2/pull/8/commits/3bee93fcffa2e4887c2422ddea99916bb83243ff#diff-b78be019f1dc6d57753ea900c3805b114cd53ab7c0db836cc081836df1b99b7aR113](https://github.com/Katended/mobilefirstproject2/pull/8/commits/3bee93fcffa2e4887c2422ddea99916bb83243ff#diff-b78be019f1dc6d57753ea900c3805b114cd53ab7c0db836cc081836df1b99b7aR113)

- Interaction 

  Added form labels to improve accessibility.

- Moving content
 Added alt text to moving logo image 
[https://github.com/Katended/mobilefirstproject2/pull/8/commits/f1bdac595432038f87fd51c400867259e177c547#diff-ba9f3fbde9c0c98a09b8fcb805a096ed053753a7b7d2844dca83ad9907e720ccR16](https://github.com/Katended/mobilefirstproject2/pull/8/commits/f1bdac595432038f87fd51c400867259e177c547#diff-ba9f3fbde9c0c98a09b8fcb805a096ed053753a7b7d2844dca83ad9907e720ccR16)
- Multimedia
 No Issues

- The basic structure of the page

   No Issues

### CODE REVIEW

**Review by Shedrack-Sunday — CHANGES_REQUESTED** [review]
Hi @Katended 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request 🔴 

You have submitted a project, that does not have the commit of your coding partner. This is a pair programming project and should have committed from both

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by tugsem** [comment]
##  STATUS: REQUIRED CHANGES ♻️
Hello @Katended  and @samiullah12345678 👋 , 

Good job so far! 👏 
There are some issues that you still need to work on to go to the next project but you are almost there!

Alt Text
## Highlights 🚀 
✔️linters are passing
✔️ Correct use of GitHub flow
✔️professional documentation
## Required Changes ♻️
- Nice report overall, however when I check the color-contrast ratio, I see 4 failing elements. You can check them too using this site: https://www.aditus.io/button-contrast-checker/. Kindly fix this.
- Contrast ratio should be at least 4.5:1.
image
image
image
image


## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by samiullah12345678** [comment]
Hello sir changes made and now with zero fails on the same site

**Comment by samiullah12345678** [comment]
Screenshot 2023-04-11 at 1 34 35 PM

**Comment by samiullah12345678** [comment]
Screenshot 2023-04-12 at 9 24 24 PM

**Pull request merged**
